# set TARGET_HOST to dns/ip of proxy
# set LOGSTASH_HOST to dns/ip of logstash host
#
# TODO:
#   Multiple -f overides are not working with the network driver
#   This seems to have been fixed in docker-compose git repo, but not yet released

version: '2'

networks:
  appnet:
    driver: bridge

volumes:
  nginx_config:
  nginx_releasenote:
  ldap_db:
  ldap_static:
  gerrit_mysql_data:
  git_repos:
  gerrit_review_site:
  sensu_api_conf:
  sensu_server_conf:
  sensu_client_conf:
  sensu_rabbitmq_data:
  sensu_redis_data:
  sonar_mysql_data:
  sonar_data:
  sonar_extensions:
  sonar_logs:
  jenkins_home:
  nexus_sonatype_work:
  selenium-config-vol:
  elasticsearch_data:

services:
  elasticsearch:
    container_name: elasticsearch
    restart: always
    image: elasticsearch:2.1.1
    networks:
      - appnet
    command: elasticsearch -Des.network.host=0.0.0.0
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
  
  logstash:
    container_name: logstash
    restart: always
    image: accenture/adop-logstash:0.1.0
    networks:
      - appnet
    environment:
      - "constraint:tier==public"
      - LS_HEAP_SIZE=1024m
    ports:
      - "12201:12201/udp"
      - "25826:25826/udp"
      - "5000:5000/tcp"
  
  kibana:
    container_name: kibana
    restart: always
    image: kibana:4.3.1
    networks:
      - appnet
    command: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - "5601:5601"

  proxy:
    container_name: proxy
    restart: always
    image: accenture/adop-nginx:0.1.0
    #source https://github.com/Accenture/adop-nginx.git
    build: ./images/adop-nginx/
    networks: 
      - appnet
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_config:/etc/nginx
      - nginx_releasenote:/usr/share/nginx/html
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://${LOGSTASH_HOST}:25826"
        syslog-tag: "proxy"
    environment:
      - "constraint:tier==public"
      - "LDAP_SERVER=ldap:389"
      - "LDAP_USERNAME=cn=admin,${LDAP_FULL_DOMAIN}"
      - "LDAP_PASSWORD=${LDAP_PWD}"
      - "LDAP_USER_BASE_DN=ou=people,${LDAP_FULL_DOMAIN}"
      - "LDAP_GROUP_ATTRIBUTE=member"
      - "LDAP_USER_ID_ATTRIBUTE=cn"
      - "LDAP_USER_OBJECT_CLASS=inetOrgPerson"

  ldap:
    container_name: ldap
    restart: always
    image: accenture/adop-ldap:0.1.0
    #source https://github.com/Accenture/adop-ldap.git
    build: ./images/adop-ldap/
    networks:
      - appnet
    expose:
      - "389"
    volumes:
      - ldap_db:/var/lib/ldap
      - ldap_static:/etc/ldap
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://${LOGSTASH_HOST}:25826"
        syslog-tag: "proxy"
    environment:
      SLAPD_PASSWORD: ${LDAP_PWD}
      SLAPD_DOMAIN: ${LDAP_DOMAIN}
      SLAPD_FULL_DOMAIN: ${LDAP_FULL_DOMAIN}

  gerrit-mysql:
    container_name: gerrit-mysql
    restart: always
    image: mysql:5.6.25
    networks:
      - appnet
    expose:
      - "3306"
    volumes:
      - gerrit_mysql_data:/var/lib/mysql
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://${LOGSTASH_HOST}:25826"
        syslog-tag: "proxy"
    environment:
      MYSQL_ROOT_PASSWORD: "Password01"
      MYSQL_USER: ${GERRIT_MYSQL_USER}
      MYSQL_PASSWORD: ${GERRIT_MYSQL_PASSWORD}
      MYSQL_DATABASE: ${GERRIT_MYSQL_DATABASE}

  gerrit:
    container_name: gerrit
    restart: always
    image: accenture/adop-gerrit:0.1.0
    #source https://github.com/Accenture/adop-gerrit.git
    build: ./images/adop-gerrit/
    privileged: true
    networks:
      - appnet
    expose:
      - "8080"
      - "29418"
    user: root
    volumes:
      - git_repos:/var/git/repos 
      - gerrit_review_site:/var/gerrit/review_site 
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://${LOGSTASH_HOST}:25826"
        syslog-tag: "proxy"
    environment:
      - "affinity:container==gerrit-mysql"
      - "REPO_PATH=/var/git/repos"
      - "WEBURL=http://${TARGET_HOST}/gerrit"
      - "DATABASE_TYPE=mysql"
      - "DB_HOSTNAME=gerrit-mysql"
      - "DB_PORT=3306"
      - "DB_NAME=${GERRIT_MYSQL_DATABASE}"
      - "DB_USER=${GERRIT_MYSQL_USER}"
      - "DB_PASSWORD=${GERRIT_MYSQL_PASSWORD}"
      - "AUTH_LOGOUTURL=http://${TARGET_HOST}/gerrit"
      - "AUTH_TYPE=LDAP"
      - "LDAP_SERVER=ldap:389"
      - "LDAP_ACCOUNTBASE=${LDAP_FULL_DOMAIN}"
      - "LDAP_ACCOUNTPATTERN=(cn=$${username})"
      - "LDAP_ACCOUNTFULLNAME=$${cn}"
      - "LDAP_ACCOUNTEMAILADDRESS=mail"
      - "LDAP_USERNAME=cn=admin,${LDAP_FULL_DOMAIN}"
      - "LDAP_PASSWORD=${LDAP_PWD}"
      - "LDAP_GROUPBASE=ou=groups,${LDAP_FULL_DOMAIN}"
      - "LDAP_GROUPPATTERN=(cn=$${groupname})"
      - "LDAP_GROUPMEMBERPATTERN=(uniqueMember=$${dn})"
      - "HTTPD_LISTENURL=proxy-http://0.0.0.0:8080/gerrit"
      - "USER_NAME=${GERRIT_USER_NAME}"
      - "USER_EMAIL=${GERRIT_USER_EMAIL}"
      - "DOWNLOAD_SCHEME=http"

  sensu-uchiwa:
    container_name: sensu-uchiwa
    restart: always
    image: sstarcher/uchiwa
    networks:
      - appnet
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://${LOGSTASH_HOST}:25826"
        syslog-tag: "proxy"
    environment:
      SENSU_HOSTNAME: sensu-api
    expose:
      - "3000"

  sensu-api:
    container_name: sensu-api
    restart: always
    image: accenture/adop-sensu:0.1.0
    #source https://github.com/Accenture/adop-sensu.git
    build: ./images/adop-sensu/
    networks:
      - appnet
    command: api
    expose:
      - "4567"
    volumes:
      - sensu_api_conf:/etc/sensu/conf.d
    environment:
      RABBITMQ_HOST: sensu-rabbitmq
      REDIS_HOST: sensu-redis

  sensu-server:
    container_name: sensu-server
    restart: always
    image: accenture/adop-sensu:0.1.0
    #source https://github.com/Accenture/adop-sensu.git
    build: ./images/adop-sensu/
    networks:
      - appnet
    command: server
    volumes:
      - sensu_server_conf:/etc/sensu/conf.d
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://${LOGSTASH_HOST}:25826"
        syslog-tag: "proxy"
    environment:
      CLIENT_NAME: core
      API_HOST: sensu-api
      RABBITMQ_HOST: sensu-rabbitmq
      REDIS_HOST: sensu-redis

  sensu-client:
    container_name: sensu-client
    restart: always
    image: accenture/adop-sensu:0.1.0
    #source https://github.com/Accenture/adop-sensu.git
    build: ./images/adop-sensu/
    networks:
      - appnet
    command: client
    volumes:
      - sensu_client_conf:/etc/sensu/conf.d
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://${LOGSTASH_HOST}:25826"
        syslog-tag: "proxy"
    environment:
      CLIENT_NAME: core
      RABBITMQ_HOST: sensu-rabbitmq
      JENKINS_PREFIX: jenkins
      CLIENT_SUBSCRIPTIONS: "proxy,gerrit,jenkins,nexus,sonarqube,sensu,kibana"

  sensu-rabbitmq:
    container_name: sensu-rabbitmq
    restart: always
    image: rabbitmq:3.5.7-management
    networks:
      - appnet
    expose:
      - "5672"
      - "5671"
      - "15672"
      - "15671"
    volumes:
      - sensu_rabbitmq_data:/var/lib/rabbitmq
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://${LOGSTASH_HOST}:25826"
        syslog-tag: "proxy"

  sensu-redis:
    container_name: sensu-redis
    restart: always
    image: redis:3.0.7
    networks:
      - appnet
    expose:
      - "6379"
    volumes:
      - sensu_redis_data:/data
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://${LOGSTASH_HOST}:25826"
        syslog-tag: "proxy"

  sonar-mysql:
    container_name: sonar-mysql
    restart: always
    image: mysql:5.6.25
    networks:
      - appnet
    expose:
      - "3306"
    volumes:
      - sonar_mysql_data:/var/lib/mysql 
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://${LOGSTASH_HOST}:25826"
        syslog-tag: "proxy"
    environment: 
      MYSQL_ROOT_PASSWORD: "sonar"
      MYSQL_USER: ${SONAR_MYSQL_USER}
      MYSQL_PASSWORD: ${SONAR_MYSQL_PASSWORD}
      MYSQL_DATABASE: ${SONAR_MYSQL_DATABASE}

  sonar:
    container_name: sonar
    restart: always
    image: accenture/adop-sonar:0.1.0
    #source https://github.com/Accenture/adop-sonar.git
    build: ./images/adop-sonar/
    networks:
      - appnet
    expose:
      - "9000"
    volumes:
      - sonar_data:/opt/sonarqube/data
      - sonar_extensions:/opt/sonarqube/extensions 
      - sonar_logs:/opt/sonarqube/logs
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://${LOGSTASH_HOST}:25826"
        syslog-tag: "proxy"
    environment:
      - "affinity:container==sonar-mysql"
      - "LDAP_URL=ldap://ldap:389"
      - "LDAP_BIND_DN=cn=admin,${LDAP_FULL_DOMAIN}"
      - "LDAP_BIND_PASSWORD=${LDAP_PWD}"
      - "LDAP_USER_BASE_DN=ou=people,${LDAP_FULL_DOMAIN}"
      - "LDAP_USER_REQUEST=(&(objectClass=inetOrgPerson)(uid={login}))"
      - "LDAP_USER_REAL_NAME_ATTRIBUTE=displayName"
      - "LDAP_USER_EMAIL_ATTRIBUTE=mail"
      - "LDAP_GROUP_BASE_DN=ou=groups,${LDAP_FULL_DOMAIN}"
      - "LDAP_GROUP_REQUEST=(&(objectClass=groupOfUniqueNames)(uniqueMember={dn}))"
      - "LDAP_GROUP_ID_ATTRIBUTE=cn"
      - "SONARQUBE_JDBC_URL=jdbc:mysql://sonar-mysql:3306/${SONAR_MYSQL_DATABASE}?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true"

  jenkins:
    container_name: jenkins
    restart: always
    image: accenture/adop-jenkins:0.1.0
    #source https://github.com/Accenture/adop-jenkins.git
    ###TODO - THIS DOESNT WORK build: ./images/adop-jenkins/
    networks:
      - appnet
    expose:
      - "8080"
      - "50000"
    privileged: true
    user: root 
    volumes:
      - jenkins_home:/var/jenkins_home 
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://${LOGSTASH_HOST}:25826"
        syslog-tag: "proxy"
    environment:
      JENKINS_OPTS: "--prefix=/jenkins"
      ROOT_URL: "http://${TARGET_HOST}/jenkins/"
      LDAP_SERVER: "ldap:389"
      LDAP_ROOTDN: "${LDAP_FULL_DOMAIN}"
      LDAP_USER_SEARCH_BASE: "ou=people"
      LDAP_USER_SEARCH: "uid={0}"
      LDAP_GROUP_SEARCH_BASE: "ou=groups"
      LDAP_GROUP_SEARCH_FILTER: ""
      LDAP_GROUP_MEMBERSHIP_FILTER: ""
      LDAP_MANAGER_DN: "cn=admin,${LDAP_FULL_DOMAIN}"
      LDAP_MANAGER_PASSWORD: ${LDAP_PWD}
      LDAP_INHIBIT_INFER_ROOTDN: "false"
      LDAP_DISABLE_MAIL_ADDRESS_RESOLVER: "false"
      LDAP_DISPLAY_NAME_ATTRIBUTE_NAME: "displayName"
      LDAP_MAIL_ADDRESS_ATTRIBUTE_NAME: "mail"
      GERRIT_HOST_NAME: "gerrit"
      GERRIT_FRONT_END_URL: "http://gerrit:8080/gerrit"
      SONAR_SERVER_URL: "http://sonar:9000/sonar/"
      SONAR_ACCOUNT_LOGIN: ${SONAR_ACCOUNT_LOGIN}
      SONAR_ACCOUNT_PASSWORD: ${SONAR_ACCOUNT_PASSWORD}
      SONAR_DB_URL: "jdbc:mysql://sonar-mysql:3306/sonar?useUnicode=true&amp;characterEncoding=utf8"
      SONAR_DB_LOGIN: ${SONAR_DB_LOGIN}
      SONAR_DB_PASSWORD: ${SONAR_DB_PASSWORD}
      SONAR_PLUGIN_VERSION: ""
      SONAR_ADDITIONAL_PROPS: ""
      SONAR_RUNNER_VERSION: "2.4"
      ANT_VERSION: "1.9.4"
      MAVEN_VERSION: "3.0.5"
      NODEJS_VERSION: "0.12.2"
      NODEJS_GLOBAL_PACKAGES: "grunt-cli@~0.1.13 bower@~1.3.12 plato@~1.2.1"
      NODEJS_PACKAGES_REFRESH_HOURS: "72"
      GIT_GLOBAL_CONFIG_NAME: "ADOP Jenkins"
      GIT_GLOBAL_CONFIG_EMAIL: "jenkins@${LDAP_DOMAIN}"
      DOCKER_TLS_VERIFY: ${DOCKER_TLS_VERIFY}
      DOCKER_HOST: ${DOCKER_HOST}
      DOCKER_CLIENT_CERT_PATH: ${DOCKER_CLIENT_CERT_PATH}
      DOCKER_NETWORK_NAME: "appnet"

  jenkins-slave:
    container_name: jenkins-slave
    restart: always
    image: accenture/adop-jenkins-slave:0.1.3
    networks:
      - appnet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://${LOGSTASH_HOST}:25826"
        syslog-tag: "proxy"
    privileged: true
    environment:
      SLAVE_LABELS: "aws ldap java8 docker"

  selenium-hub:
    container_name: selenium-hub
    restart: always
    image: selenium/hub:2.46.0
    networks:
      - appnet
    expose:
      - "4444"
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://${LOGSTASH_HOST}:25826"
        syslog-tag: "proxy"

  selenium-node-chrome:
    container_name: selenium-node-chrome
    restart: always
    image: selenium/node-chrome:2.46.0
    networks: 
      - appnet
    volumes:
      - ./volumes/selenium-config-vol:/var/selenium-config
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://${LOGSTASH_HOST}:25826"
        syslog-tag: "proxy"
    environment:
      SE_OPTS: "-nodeConfig /var/selenium-config/config-chrome.json"
      HUB_PORT_4444_TCP_ADDR: "selenium-hub"
      HUB_PORT_4444_TCP_PORT: "4444"

  selenium-node-firefox:
    container_name: selenium-node-firefox
    restart: always
    image: selenium/node-firefox:2.46.0
    networks:
      - appnet
    volumes:
      - ./volumes/selenium-config-vol:/var/selenium-config
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://${LOGSTASH_HOST}:25826"
        syslog-tag: "proxy"
    environment:
      SE_OPTS: "-nodeConfig /var/selenium-config/config-firefox.json"
      HUB_PORT_4444_TCP_ADDR: "selenium-hub"
      HUB_PORT_4444_TCP_PORT: "4444"

  nexus:
    container_name: nexus
    restart: always
    image:  accenture/adop-nexus:0.1.0
    networks:
      - appnet
    expose:
      - "8081"
    volumes:
      - nexus_sonatype_work:/sonatype-work
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://${LOGSTASH_HOST}:25826"
        syslog-tag: "proxy"
    environment:
      NEXUS_BASE_URL: "http://${TARGET_HOST}/nexus"
      LDAP_SEARCH_BASE: "${LDAP_FULL_DOMAIN}"
      LDAP_ENABLED: "true"
      LDAP_URL: "ldap"
      LDAP_BIND_DN: "cn=admin,${LDAP_FULL_DOMAIN}"
      LDAP_USER_PASSWORD_ATTRIBUTE: "userPassword"
      LDAP_USER_BASE_DN: "ou=people"
      LDAP_GROUP_BASE_DN: "ou=groups"
      LDAP_BIND_PASSWORD: ${LDAP_PWD}
